### ISSUE TITLE
Can you please upload the appropriate Klipper macros?

### ISSUE THREAD

**Issue by Phill93** [ThatGuyHes/Dual-Extruder-X4#1]
Hello,

would like to rebuild the project and would need the Klipper Macros, can you please upload them?

Greetings

Phill93

**Comment by ThatGuyHes** [comment]
Hi,

I'm using RepRapFirmware.

I will upload the firmware directory. Hopefully you can decipher it. :)

**Comment by Phill93** [comment]
Thank you, very much. I will take a look.
